name: CI - Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_IMAGE }}
  DOCKERHUB_TAG: ${{ secrets.DOCKERHUB_TAG }}
  DOCKER_CONTAINER_NAME: ${{ secrets.DOCKER_CONTAINER_NAME }}
  DOCKER_CONTAINER_PORT: ${{ secrets.DOCKER_CONTAINER_PORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_IMAGE }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          # Push only if not PR
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          # If tag needs to be manual, uncomment below line, comment above line
          # tags: ${{ DOCKERHUB_USERNAME }}/${{ DOCKERHUB_IMAGE }}:${{ DOCKERHUB_TAG }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
